### ISSUE TITLE
Alpha release checklist.

### ISSUE THREAD

**Issue by danielvaijk** [danielvaijk/hades#10]
package.json

- [x] Change `license` property value (to `MIT`?).
- [x] Set `private` to `false`.
- [x] Bump `version` to `0.1.0`
- [ ] Remove `engines` property.

repository

- [ ] Create tag `0.1.0`
